name: 'oranc'
description: 'nix build with the help of caching with oranc'
author: 'Lin Yinfeng'
inputs:
  registry:
    required: true
    description: 'oci registry to use'
    default: 'ghcr.io'
  repositoryPart1:
    required: true
    description: 'first part of the repository name'
    default: '${{ github.repository_owner }}'
  repositoryPart2:
    required: true
    description: 'second part of the repository name'
    default: 'oranc-cache'
  upstream:
    required: true
    description: 'space-separated list of cache upstreams'
    default: 'https://cache.nixos.org'
  orancType:
    required: true
    description: 'either "docker" or "url"'
    default: 'docker'
  orancContainer:
    required: false
    description: 'docker container id of oranc'
  orancUrl:
    required: false
    description: 'docker container name or id of oranc'
  orancLog:
    required: true
    description: 'log string used in pushing'
    default: 'oranc=info'
  anonymous:
    required: true
    description: 'weather remain anonymous'
    default: 'false'
  username:
    required: false
    description: 'oci registry username'
    default: '${{ github.actor }}'
  password:
    required: false
    description: 'oci registry password'
    default: '${{ github.token }}'
  signingKey:
    required: true
    description: 'nix signing key'
  parallel:
    required: true
    description: 'number of workers to do parallel pushing'
    default: '4'
  maxRetry:
    required: true
    description: 'max retry number of requests'
    default: '3'
  zstdLevel:
    required: true
    description: 'zstd compression level'
    default: '3'
runs:
  using: 'node16'
  main: 'dist/index.js'
  # same entry point for simplicity
  post: 'dist/index.js'
