name: 'oranc'
description: 'nix build with the help of caching with oranc'
author: 'Lin Yinfeng'
inputs:
  registry:
    required: true
    description: 'oci registry to use'
    default: 'ghcr.io'
  repositoryPart1:
    required: true
    description: 'first part of the repository name'
    default: '${{ github.repository_owner }}'
  repositoryPart2:
    required: true
    description: 'second part of the repository name'
    default: 'oranc-cache'
  upstream:
    required: true
    description: 'space-separated list of cache upstreams'
    default: 'https://cache.nixos.org'
  orancServerType:
    required: true
    description: 'either "docker" or "url"'
    default: 'docker'
  orancServerContainer:
    required: false
    description: 'docker container id of oranc'
  orancServerUrl:
    required: false
    description: 'docker container name or id of oranc'
  orancCli:
    required: true
    description: 'oranc CLI package to use'
    default: 'github:linyinfeng/oranc'
  orancLog:
    required: true
    description: 'log string used in pushing'
    default: 'oranc=info'
  orancCliExtraArgs:
    description: 'arguments pass to oranc cli, URL-encoded, separated by space'
    default: ''
  anonymous:
    required: true
    description: 'weather remain anonymous'
    default: 'false'
  username:
    required: false
    description: 'oci registry username'
    default: '$'
  password:
    required: false
    description: 'oci registry password'
    default: '${{ github.token }}'
  signingKey:
    required: true
    description: 'nix signing key'
  parallel:
    required: true
    description: 'number of workers to do parallel pushing'
    default: '4'
  maxRetry:
    required: true
    description: 'max retry number of requests'
    default: '3'
  zstdLevel:
    required: true
    description: 'zstd compression level'
    default: '3'
  initialize:
    required: true
    description: 'ensure that nix-cache-info file is initialized'
    default: 'false'
  forceInitialize:
    required: true
    description: 'force initialization'
    default: 'false'
  initializePriority:
    required: true
    description: 'priority in nix-cache-info'
    default: '41'
  initializeMassQuery:
    required: true
    description: 'mass query in nix-cache-info'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
  # same entry point for simplicity
  post: 'dist/index.js'
